nelmio_api_doc:
    documentation:
        info:
            title: Easy School API
            description: a simple API exercise to handle students and grades
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
            - ^/students
            - ^/grades
